const data = [
  // {
  //   id: 0,
  //   name: 'projeto 1',
  //   image: 'https://i0.wp.com/www.evolvedcontact.com.au/articles/wp-content/uploads/2020/04/81-817751_quiz-time-announcement-poster-neon-signboard-vector-quiz.png?fit=1024%2C417&ssl=1',
  //   urlGitHub: '',
  //   urlApication: '',
  //   description: 'teste',
  //   stacks: ['HTML', 'CSS'],
  //   category: 'front',s
  // },
  {
    id: 0,
    name: '',
    projectName: '',
    image: '',
    gif: '',
    urlGitHub: '',
    urlApication: '',
    description: '',
    stacks: [],
    skills: '',
    category: '',
  },
  {
    id: 1,
    name: 'Pixels Art',
    projectName: 'pixels-art',
    image: 'https://i.pinimg.com/originals/60/96/24/60962403310debc750aefcff61e075a5.jpg',
    gif: 'https://github.com/Abreupamm/project-pixels-art/raw/pamela-abreu-pixels-art/pixel-art.gif',
    urlGitHub: 'https://github.com/Abreupamm/project-pixels-art',
    urlApication: 'https://abreupamm.github.io/project-pixels-art/',
    description: 'O Pixel-Art é uma página web que contém uma paleta de cores funcional que poderá ser utilizada para criar desenhos em pixels.',
    stacks: ['javascript', 'css', 'html'],
    skills: 'Manipular o DOM, eventos e LocalStorange com javascript',
    category: 'front',
  },
  {
    id: 2,
    name: 'Lista de Tarefas',
    projectName: 'project-todo-list',
    image: 'https://st2.depositphotos.com/6628792/9630/v/600/depositphotos_96302366-stock-illustration-to-do-list-theme-flat.jpg',
    gif: 'https://github.com/Abreupamm/project-todo-list/raw/pamela-abreu-todo-list/todo-list.gif',
    urlGitHub: 'https://github.com/Abreupamm/project-todo-list',
    urlApication: 'https://abreupamm.github.io/project-todo-list/',
    description: 'O Projeto Todo-list é uma página web que contém um campo para inserir uma tarefa, podendo escolher uma categiria. Suas tarefas ficam salvas e você também pode excluir ou marcar como finalizada.',
    stacks: ['javascript', 'css', 'html'],
    skills: 'Manipular o DOM, eventos e LocalStorange com javascript',
    category: 'front',
  },
  {
    id: 3,
    name: 'MongoDB Commerce',
    projectName: 'mongodb-commerce',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8qjYQfVCGh2fR7KAZLQ-dN--UyWCzWqO-Ms0jgDp9TWDqhqmYS1T0uZqfH2fhKQ9Tk0s&usqp=CAU',
    gif: '',
    urlGitHub: 'https://github.com/Abreupamm/mongodb-commerce',
    urlApication: '',
    description: 'Este projeto foi desenvolvido utilizando o banco de dados MongoDB, a ideia era trabalhar com alguns dados do cardápio do McDonalds: ingredientes, valores nutricionais e dados fictícios de vendas. O desafio proposto era alterar documentos utilizando métodos de update com operadores simples, complexos e modificadores.',
    stacks: ['mongodb', 'docker'],
    skills: 'Subir o banco utilizando docker e construir queries para fazer buscas, alterações, e deletar informações do banco de dados.',
    category: 'back',
  },
  {
    id: 4,
    name: 'TrybeTunes',
    projectName: 'trybetunes',
    image: 'https://files.tecnoblog.net/wp-content/uploads/2019/05/podcast-iphone-700x529.jpg',
    gif: '',
    urlGitHub: 'https://github.com/Abreupamm/project-TrybeTunes',
    urlApication: '',
    description: 'Nesse projeto utilizei a biblioteca React para criar uma aplicação onde é possível pesquisar e listar álbuns e músicas de várias bandas e artistas. É possível até mesmo ouvir o preview de cada música. Além disso, você também poderá favoritar suas músicas preferidas. Tudo isso foi dividido em várias rotas, cada uma responsável por uma parte da funcionalidade.',
    stacks: ['react', 'css', 'javascript'],
    skills: 'Conceitos de React Router e lifecycle-methods',
    category: 'front',
  },

  
];

export default data;