const data = [
  // {
  //   id: 0,
  //   name: 'projeto 1',
  //   image: 'https://i0.wp.com/www.evolvedcontact.com.au/articles/wp-content/uploads/2020/04/81-817751_quiz-time-announcement-poster-neon-signboard-vector-quiz.png?fit=1024%2C417&ssl=1',
  //   urlGitHub: '',
  //   urlApication: '',
  //   description: 'teste',
  //   stacks: ['HTML', 'CSS'],
  //   category: 'front',s
  // },
  {
    id: 1,
    name: 'Pixels Art',
    projectName: 'pixels-art',
    image: 'https://i.pinimg.com/originals/60/96/24/60962403310debc750aefcff61e075a5.jpg',
    gif: 'https://github.com/Abreupamm/project-pixels-art/raw/pamela-abreu-pixels-art/pixel-art.gif',
    urlGitHub: 'https://github.com/Abreupamm/project-pixels-art',
    urlApication: 'https://abreupamm.github.io/project-pixels-art/',
    description: 'O Pixel-Art é uma página web que contém uma paleta de cores funcional que poderá ser utilizada para criar desenhos em pixels.',
    stacks: ['javascript', 'css', 'html'],
    skills: 'Manipular o DOM, eventos e LocalStorange com javascript',
    category: 'front',
  },
  {
    id: 2,
    name: 'Lista de Tarefas',
    projectName: 'todo-list',
    image: '',
    gif: 'https://github.com/Abreupamm/project-todo-list/raw/pamela-abreu-todo-list/todo-list.gif',
    urlGitHub: 'https://github.com/Abreupamm/project-todo-list',
    urlApication: 'https://abreupamm.github.io/project-todo-list/',
    description: 'O Projeto Todo-list é uma página web que contém um campo para inserir uma tarefa, podendo escolher uma categiria. Suas tarefas ficam salvas e você também pode excluir ou marcar como finalizada.',
    stacks: ['javascript', 'css', 'html'],
    skills: 'Manipular o DOM, eventos e LocalStorange com javascript',
    category: 'front',
  },
  {
    id: 3,
    name: 'MongoDB Commerce',
    projectName: 'mongodb-commerce',
    image: '',
    gif: '',
    urlGitHub: 'https://github.com/Abreupamm/mongodb-commerce',
    urlApication: '',
    description: 'vgzdxfcasfdcasdfasfas a  asfafhh fgdfg dgdfg dgdsgs dgdsgsd g sgdsgsgtew f fafsarfesfdsa f s sgdgs gseg  efsg sdgsd s gsdg   whghfhd wqe wr wew ',
    stacks: ['mongodb', 'docker'],
    skills: 'Construir queries para fazer buscas, alterações, e deletar informações do banco de dados',
    category: 'back',
  },
];

export default data;